### ISSUE TITLE
Idea: change quoting method

### ISSUE THREAD

**Issue by phildenhoff** [c6p/logseq-hypothesis#13]
Not an issue so much as a discussion topic. I'm wondering what your thoughts are on (optionally?) changing the way highlights & annotations are decorated.

Right now, quoting works like this:

```md
Types of notes

- 📌 **highlight**
- 📝
  - **annotation** - if under an highlight
  - **reply** - if a child
  - **page note** - if not a child
- 🗑️ *deleted* note
```

Personally, I'm not a huge fan of that — since highlights are text quotes, I'd like to render them as Logseq quotes using the `> ` character. Also, since my annotations are really notes, I don't want them decorated with an emoji at all

In summary, I'd like this:
![Screen Shot 2022-05-05 at 10 28 05 AM](https://user-images.githubusercontent.com/17505728/166979388-457b9184-1ade-45aa-ae14-03ce95db9ccb.png)

Instead of this:
![Screen Shot 2022-05-05 at 10 28 33 AM](https://user-images.githubusercontent.com/17505728/166979403-50f80ac7-cc33-4f58-a8c5-261c97c631f9.png)

What do you think about that? I've already done this work on [my fork, in a branch](https://github.com/phildenhoff/logseq-hypothesis/pull/1) and I'll continue using that method, but right now it's tied into some changes with how the menu is rendered, which I'd like to make sure we get back into your mainline.

**Comment by c6p** [comment]
Hey @phildenhoff,

Thanks for all the work.

Please check out my review on your fork. I want to provide a more general form of templating, then we may have your decorations as one example of possible customizations.

For other changes, please submit them as PRs.

Cheers

**Comment by phildenhoff** [comment]
Thanks for taking a look at it — do you have idea on how you'd like to provide the formatting? I can see that quickly becoming a complicated feature (and not something I'd want to implement without a plan)

**Comment by c6p** [comment]
What I have in mind is actually quite simple. Just letting user set a custom format for each of the 5 annotation types, maybe kept in a `annotationFormat` setting. For example:
```
📌 {{highlight}}
📝 {{annotation}}
📝 {{reply}}
📝 {{pageNote}}
🗑️ {{deleted}}
```
I'm not exactly sure on `{{`. For your case:
```
> {{highlight}}
{{annotation}}
{{reply}}
{{pageNote}}
🗑️ {{deleted}}
```
Or something similar. It should be enough for most use cases.

**Comment by c6p** [comment]
I've moved all under the settings menu. Check out v0.2.3 and README.md.

Cheers

**Comment by phildenhoff** [comment]
That works great, thank you!!
