### ISSUE TITLE
Notes are not created as child blocks

### ISSUE THREAD

**Issue by krillin666** [c6p/logseq-hypothesis#17]
Hi @c6p, thank you for this amazing plugin !

I've noticed one bug since the last update. When I have a highlight that has a comment, when it gets imported to Logseq I expect it to have the following format:

```markdown
- > An highlight
    - A commentary 
```
So basically, that any commentary gets added to the respective highlight under its child block

However, what I get is all in one block:

```markdown
- An highlight
A commentary
```

Thank you for your time !

**Comment by c6p** [comment]
Hey @krillin666,

Annotations are placed within the same block, while replies are children.

![resim](https://user-images.githubusercontent.com/80478/170268806-487d7bf1-cf6c-4e47-9ae2-f6d491654c4c.png)

```
- It focuses on privacy, longevity
Annotation
  - Reply
```

Is your commentary an annotation or a reply in hypothes.is terms? If it is an annotation, the current behavior is correct. Though, in the future, I may add custom behavior where annotation is also a child of a highlight.

```
- It focuses on privacy, longevity
  - Annotation
    - Reply
```

**Comment by krillin666** [comment]
I'm sorry, I thought this was a bug. Then I think this issue might be turned into a feature request :sweat_smile:  ?

**Comment by c6p** [comment]
Come to think of it, hypothesis does not make any distinction between a highlight and an annotation. Returning it in the same row with a single ID. Placing an annotation into another block in Logseq, would make tracking it impossible. So, it won't be fixed. Sorry, @krillin666.

You can modify the templates to make it visually more distinct, though.

Is there anything I could do, to make the current behavior more bearable?

Cheers

**Comment by krillin666** [comment]
> Come to think of it, hypothesis does not make any distinction between a highlight and an annotation. Returning it in the same row with a single ID. Placing an annotation into another block in Logseq, would make tracking it impossible. So, it won't be fixed. Sorry, @krillin666.
> 
> You can modify the templates to make it visually more distinct, though.
> 
> Is there anything I could do, to make the current behavior more bearable?
> 
> Cheers

Actually, there is ! Is it possible to add a vertical space (*shift+enter)* in the block when we have highlight+annotation ?
Because, what is happening now is that since there's no space between the highlight and the annotation, the annotation gets blended and rendered has a highlight.

Basically, this is what's happening:
```markdown
> It focuses on privacy, longevity
Annotation
```
And so that `Annotation` is not rendered has a highlight due to the settings having `>` before the highlight, I have to manually add a `shift+enter` vertical space like this:

```markdown
> It focuses on privacy, longevity

Annotation
```
Thank you for your time !

**Comment by c6p** [comment]
You are right, I'm going to add a line break before annotation in the next version.

**Comment by c6p** [comment]
@yhkang, from now on, you can use `\n` in annotation formats to add newlines where you want.
