### ISSUE TITLE
Where is "Fetch Updates"?

### ISSUE THREAD

**Issue by huyz** [c6p/logseq-hypothesis#20]
I installed and configured the plugin.  I see a Hypothes.is icon at the top-right of each page, but nothing happens when I click it.  And I can't find `Fetch Updates` in menus or the command palette.

I'm not sure how to get it all started.

Some screenshots of where these commands may be useful.

**Comment by c6p** [comment]
It is `Fetch latest notes` now.

You should set your username and API key as in README by clicking `Settings`, then click `Fetch latest notes` to fetch all annotations. To update, press the same button too.

Sorry for the confusion. I'll update the README when I have time.
