### ISSUE TITLE
Icon stands out too much

### ISSUE THREAD

**Issue by macedotavares** [c6p/logseq-hypothesis#4]
Hi!

First, I want to thank you for this. It was your plugin that actually got me started on Hypthes.is.
I've been using it for a couple of days, and functionally, I have found nothing wrong with it.

I just have an issue with the icon's appearance and behaviour. It doesn't really fit in.

My suggestion would be to use a monochromatic version of the icon, one that:
- aligns better with all the others
- takes colour from the theme
- reacts to hover

Also, given the small size of the icon, that pointy bit of the callout throws the whole thing out of alignment. I don't know Hypothes.is's brand guidelines, but maybe you could just keep the `h.`.

I know my way around Sketch and Photoshop. Let me know if you need any help.

Cheers.

**Comment by c6p** [comment]
[Branding page](https://web.hypothes.is/brand/) has also black and white variants. However, the best solution would be to convert it into a font, so it can inherit current colors. [Glyphter](https://glyphter.com) can do it with ease. For the pointy part, I think [baseline](https://en.wikipedia.org/wiki/Baseline_(typography)) can be moved further up, in theory fontforge can do it, though I do not have any experience with this.

If you can create a custom font, I can use it.

**Comment by macedotavares** [comment]
Cool,

Give me a couple of days and I'll get back to you on this.

Cheers!

**Comment by macedotavares** [comment]
Here:

[hypothes_is_icon.zip](https://github.com/c6p/logseq-hypothesis/files/7492319/hypothes_is_icon.zip)

I just aligned the icon on a square (in Affinity Designer) and then used icomoon.io to generate the font.
Let me know if you run into any problems or if you need help with something else.

Cheers!

**Comment by c6p** [comment]
@macedotavares Thank you for your contribution. V0.1.5 released. It looks great now.

Take care. :smile:

**Comment by macedotavares** [comment]
> It looks great now.

Indeed it does :D

Thanks!
