### ISSUE TITLE
Use URI title as page name

### ISSUE THREAD

**Issue by rsuhada** [c6p/logseq-hypothesis#6]
First of all thank you for this extension, this is of incredible value!

I have 1.5 enhancement suggestions:

1. Would it be possible to use the URI title as the page name? The first line of the page has a nicely formated html link and I'd prefer to have the page name to be the title of the article, rather than the URL

2. For me it would be useful to automatically also link this new logseq page from the current day journal page. I think this might not be everybody's preference, but though I'd mention it.

Thank you in any case!

**Comment by c6p** [comment]
Hey @rsuhada,

I need to think about the 2nd one, but for the first one, I can add a checkbox to use page title instead of URI.

Cheers

**Comment by bepolymathe** [comment]
> * Would it be possible to use the URI title as the page name? The first line of the page has a nicely formated html link and I'd prefer to have the page name to be the title of the article, rather than the URL
> * For me it would be useful to automatically also link this new logseq page from the current day journal page. I think this might not be everybody's preference, but though I'd mention it.

Totally for that too.

**Comment by nt7** [comment]
First of all, @c6p thank you so much for this great addition to logseq, it really helps me in my workflow.

I fully agree with his suggestion by @rsuhada, 
I actually came to the repo to see if someone else would like to see this.

My main problem here is that with a long url, eg  domain.tld/sub1/sub2/sub3/sub4/xyz.html, a total of 4 of subpages are created that add no value.
If I rename the title straight after importing the new reference, then the property fields of the references are displayed (which were not shown before).

so I can either create a lot of unused subpages, or add unneeded bulk to the file.
Ideally, the title page is just the title of the website and changing it doesn't mess with the properties setting of the doc.
