### ISSUE TITLE
Account connects but annotations to not import

### ISSUE THREAD

**Issue by keelancook** [c6p/logseq-hypothesis#7]
Hello. I'm not a developer and I'm fairly new to Hypothes.is, so this may be something easy I'm missing.

I have the integration set up, and it appears to be connecting correctly. When I fetch update, it pulls in the most recent list of websites annotated. However, when I get selected page it does not grab any annotations.

It does create the page names with the URL of the website, but I'm not finding any annotations on that page. There's a chance I just don't what I'm doing and I have it set up incorrectly. Though, I wanted to see if there was a problem with  my install.

I'm running this on the most recent version of Linux Mint with the appimage of Logseq. 

Thanks for putting this together. I really do hope I can get it working with my Logseq setup!

**Comment by c6p** [comment]
Hey @keelancook

After selecting a page from the dropdown, you are clicking "get selected page" right? And resulting page is empty.

If the problem persists, could you paste part of the plugin settings to make sure the data is writtern correctly. (In Plugins page, click Open settings)

**Comment by keelancook** [comment]
Sorry for the delay. Was away from the computer for a while.

Yes, that is correct. I select an option from the drop down menu (which correctly populates from my account, so I know it's connecting at some level), and then click "get selected page" and the resulting page does not populate with any annotations. It does create the page, but it is empty.

I would be happy to paste a section of code, if you could direct me to the appropriate section in the settings. I don't know enough to read it, and that json that comes up is long enough I doubt you want me to past the whole thing in here.

Just let me know. I should be more available in the coming days.

**Comment by c6p** [comment]
No problem. From that json file, could you paste or attach first 30-40 lines of `annotations`. It should be a few lines away from the begnning. 
```json
{
  "annotations": [...]
}
```
* Is it consistently empty for any page?
* Does any errors logged in console when you "get selected page"? (ctrl+shift+i)

Happy new year btw.

**Comment by keelancook** [comment]
You got it. 

- Yes, it is consistently empty. When I hit the get selected page, it takes me to a blank page with 0 unlinked references, no title, no blocks of any kind. When I dig around in All Pages, I do find pages the it appears to pull in title with hypothes.is and the name of the article, but they are empty. I wind up have to go through a delete these in order to clean up the graph. When I click on one of these pages, though, it does have one property (the title of the article) and a "Hierarchy" toggle that breaks apart the url into various pages or links of some kind. 
- There are no errors logging that I see when I pull up the panel. It actually doesn't appear to do anything, but I may be missing something.


Here's the copied code:

`
"annotations": [
    {
      "id": "6SJRHpmgEemjDhvqmEd-GQ",
      "created": "2019-06-28T12:33:19.549074+00:00",
      "updated": "2019-06-28T12:33:19.549074+00:00",
      "uri": "https://www.washingtonpost.com/realestate/as-cities-rethink-single-family-zoning-traditional-ideas-of-the-american-dream-are-challenged/2019/06/25/8312a512-4ca3-11e9-93d0-64dbcf38ba41_story.html",
      "text": "",
      "tags": [],
      "group": "V4d7G8Ne",
      "target": [
        {
          "source": "https://www.washingtonpost.com/realestate/as-cities-rethink-single-family-zoning-traditional-ideas-of-the-american-dream-are-challenged/2019/06/25/8312a512-4ca3-11e9-93d0-64dbcf38ba41_story.html",
          "selector": [
            {
              "type": "RangeSelector",
              "endOffset": 173,
              "startOffset": 0,
              "endContainer": "/div[3]/div[2]/section[2]/div[2]/div[1]/article[1]/p[2]",
              "startContainer": "/div[3]/div[2]/section[2]/div[2]/div[1]/article[1]/p[2]"
            },
            {
              "end": 2867,
              "type": "TextPositionSelector",
              "start": 2694
            },
            {
              "type": "TextQuoteSelector",
              "exact": "“The American Dream has always been to own a home and raise your kids in a house with a yard,” said Valentine, a stay-at-home mom who lives in the Linden Hills neighborhood.",
              "prefix": " to Minneapolis public schools. ",
              "suffix": " Now, she said, she worries the "
            }
          ]
        }
      ],
      "document": {
        "title": [
          "As cities rethink single-family zoning, traditional ideas of the American Dream are challenged"
        ]
      },
      "links": {
        "html": "https://hypothes.is/a/6SJRHpmgEemjDhvqmEd-GQ",
        "incontext": "https://hyp.is/6SJRHpmgEemjDhvqmEd-GQ/www.washingtonpost.com/realestate/as-cities-rethink-single-family-zoning-traditional-ideas-of-the-american-dream-are-challenged/2019/06/25/8312a512-4ca3-11e9-93d0-64dbcf38ba41_story.html",
        "json": "https://hypothes.is/api/annotations/6SJRHpmgEemjDhvqmEd-GQ"
      },
      "flagged": false,
      "hidden": false
    },
    {
      "id": "XjVVopm4EemIKQckrRFk8A",
      "created": "2019-06-28T15:21:14.186983+00:00",
      "updated": "2019-06-28T15:21:14.186983+00:00",
      "uri": "https://www.washingtonpost.com/realestate/as-cities-rethink-single-family-zoning-traditional-ideas-of-the-american-dream-are-challenged/2019/06/25/8312a512-4ca3-11e9-93d0-64dbcf38ba41_story.html",
      "text": "",
      "tags": [],
      "group": "V4d7G8Ne",
      "target": [
        {
          "source": "https://www.washingtonpost.com/realestate/as-cities-rethink-single-family-zoning-traditional-ideas-of-the-american-dream-are-challenged/2019/06/25/8312a512-4ca3-11e9-93d0-64dbcf38ba41_story.html",
          "selector": [
            {
              "type": "RangeSelector",
              "endOffset": 154,
              "startOffset": 0,
              "endContainer": "/div[3]/div[2]/section[2]/div[2]/div[1]/article[1]/p[10]",
              "startContainer": "/div[3]/div[2]/section[2]/div[2]/div[1]/article[1]/p[10]"
            },
            {
              "end": 4335,
              "type": "TextPositionSelector",
              "start": 4181
            },
            {
              "type": "TextQuoteSelector",
              "exact": "Meanwhile, some other landlocked expensive cities struggling to create housing for moderate-income residents are exploring whether to make a similar move.",
              "prefix": "ercely criticizing the measure. ",
              "suffix": " “We are never going to achieve "
            }
          ]
        }
      ],
      "document": {
        "title": [
          "As cities rethink single-family zoning, traditional ideas of the American Dream are challenged"
        ]
      },
      "links": {
        "html": "https://hypothes.is/a/XjVVopm4EemIKQckrRFk8A",
        "incontext": "https://hyp.is/XjVVopm4EemIKQckrRFk8A/www.washingtonpost.com/realestate/as-cities-rethink-single-family-zoning-traditional-ideas-of-the-american-dream-are-challenged/2019/06/25/8312a512-4ca3-11e9-93d0-64dbcf38ba41_story.html",
        "json": "https://hypothes.is/api/annotations/XjVVopm4EemIKQckrRFk8A"
      },
      "flagged": false,
      "hidden": false
    },
    {
      "id": "byOa0Jm5Eem_qQvAUjwn2A",
      "created": "2019-06-28T15:28:51.929938+00:00",
      "updated": "2019-06-28T15:28:51.929938+00:00",
      "uri": "https://factsandtrends.net/2019/03/06/how-many-us-churches-are-actually-growing/",
      "text": "",
      "tags": [],
      "group": "V4d7G8Ne",
      "target": [
        {
          "source": "https://factsandtrends.net/2019/03/06/how-many-us-churches-are-actually-growing/",
          "selector": [
            {
              "type": "RangeSelector",
              "endOffset": 160,
              "startOffset": 109,
              "endContainer": "/div[2]/div[2]/div[1]/main[1]/article[1]/div[1]/p[4]",
              "startContainer": "/div[2]/div[2]/div[1]/main[1]/article[1]/div[1]/p[4]"
            },
            {
              "end": 973,
              "type": "TextPositionSelector",
              "start": 922
            },
            {
              "type": "TextQuoteSelector",
              "exact": "“But rapid growth through conversions is uncommon.”",
              "prefix": "e director of LifeWay Research. ",
              "suffix": "\nThe research gives a clear pict"
            }
          ]
        }
      ],
      "document": {
        "title": [
          "How Many US Churches Are Actually Growing? | Facts & Trends"
        ]
      },
      "links": {
        "html": "https://hypothes.is/a/byOa0Jm5Eem_qQvAUjwn2A",
        "incontext": "https://hyp.is/byOa0Jm5Eem_qQvAUjwn2A/factsandtrends.net/2019/03/06/how-many-us-churches-are-actually-growing/",
        "json": "https://hypothes.is/api/annotations/byOa0Jm5Eem_qQvAUjwn2A"
      },
      "flagged": false,
      "hidden": false
    },
`

**Comment by c6p** [comment]
Thanks, @keelancook. I couldn't figure out what might be the problem.

I am relocating to another city. So, I will be without my pc for about a month. Sorry for the inconvenience.

I'm on Windows 10 and still on Logseq v0.5.4. If any other Linux user have the same issue, I might also try on a VM in February.

**Comment by keelancook** [comment]
No worries! This is not a crucial tool for me, so I'm in no rush. It is a
really great idea, though, so I'd love to see you succeed in it's
development. When you get back to it, let me know if I can be of further
assistance. I'm happy to play with it on Linux and see what happens. Wish I
could add some developer muscle, but that's out of my league, I'm afraid.

Blessings and Happy New Year!

**Comment by c6p** [comment]
@keelancook, does the problem persists with the latest versions?

**Comment by keelancook** [comment]
It's working now! Thanks so much for your work on this.

I look forward to using it.

**Comment by c6p** [comment]
I'm glad that it is working now.

Cheers
